plugins {
    id 'java'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // <-- впишіть свій пакет, напр. 'ua.hotel.Main'
    mainClass = 'ua.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaExec).configureEach {
    defaultCharacterEncoding = 'UTF-8'
}
